### PR TITLE
Add INDIGO Docker

### PR DESCRIPTION
**Pull request by tail-feather**
Added Dockerfile.

This works well in my environment.

### CODE REVIEW

**Comment by rumengb** [comment]
Hi thank you! But will you explain what is the purpose of your commit?

**Comment by tail-feather** [comment]
I want to execute a build equivalent to CI in the local environment.
And our products made updating easier by using INDIGO in Docker.

**Comment by rumengb** [comment]
Have you seen in makefile: debs-docker? How is that different?

**Comment by tail-feather** [comment]
?!
Sorry, I didn't know that option.

For the build, the existing one looks good.

For `docker/raspi`, the persistence setting is done by `docker-compose.yml`, and you can operate just by copying the image as follows.

In build environment:
```
sudo docker save raspi_indigo:latest > indigo_latest.tar
```

In Raspberry Pi:
```
sudo docker load < indigo_latest.tar
```

These images are for running INDIGO alone.
And these Docker image can be register on Docker Hub.

ref: https://hub.docker.com/r/jochym/indi-docker

**Comment by rumengb** [comment]
Thank you!
This is propably a good idea :)
Let us discuss this with Peter first. I want to keep the repo as clean as
possible. maybe we can put this in a separate repo or we can keep it here.
I just want to discuss with Peter where it is best place to accommodate it
before we accept it. Is that ok?

Rumen

**Comment by tail-feather** [comment]
Of course!
I will leave it to you. :smiley:
Thank you!

**Comment by tail-feather** [comment]
Sorry, Dockerfile was missing.

**Comment by polakovic** [comment]
I think it is a good idea to create that tar from local repo instead of downloading master from github, but otherwise it is the same as we do with top level Makefile and tools/build_debs.sh. I'll try to merge your solution to existing scripts, ok?

**Comment by tail-feather** [comment]
Yes, OK.
Thank you!

**Comment by rumengb** [comment]
We have a docker build for all supported platforms. I am closing the request.

**Comment by tail-feather** [comment]
That's the good news. I'll give it a try.
Thank you!

**Pull request closed without merging**
