### PR TITLE
Add missing FITS keywords to xisf format

### PR DESCRIPTION
**Pull request by kkretzschmar**
Hi Peter,
I added FITSKeywords to the .xisf file format. This is necessary since some tools in PI (e.g. CometAlignment) rely on these FITSKeywords.  

Found that you use the observation end time for the DATE-OBS keyword. The FITS standard says that this keyword should contain the observation start time. Is there a special reason why you use the observation end time?

Best
Klaus

### CODE REVIEW

**Comment by rumengb** [comment]
Hi Klaus,
There is one thing that bothers me it is the spacing... we use "tabs" not spaces I am not sure if we follow this in all files but the code seems to be a bit misaligned. Can you fix this before I merge it?

DATE-OBS should be start i agree. This must be overlooked by us... We will address it.

**Comment by polakovic** [comment]
I'll fix tabs and look at DATE-OBS. Thank you Klaus.

**Comment by polakovic** [comment]
The problem is, that we don't have the time when exposure was started at this point :( It will be more complicated to fix it...

**Comment by kkretzschmar** [comment]
> Hi Klaus,
> There is one thing that bothers me it is the spacing... we use "tabs" not spaces I am not sure if we follow this in all files but the code seems to be a bit misaligned. Can you fix this before I merge it?

Yes, I'll pay attention on it next time. It must be a standard setting (replacing tabs by spaces) of my editor.

**Comment by kkretzschmar** [comment]
> The problem is, that we don't have the time when exposure was started at this point :( It will be >more complicated to fix it...
I used date_time_start for the FITS keyword but noticed, that this is the same as date_time_end.

Thanks for fixing the code style ;)...

**Comment by polakovic** [comment]
It is not the same, it is reduced by exposure time :) But it is not perfect solution, just better than nothing...

**Pull request merged**
