### PR TITLE
Add support for Pegasus Pocket Powerbox Advanced

### PR DESCRIPTION
**Pull request by aaronfreimark**
I have a PPBA and wanted it to work :-) I created this by modifying the example in indigo_drivers/aux_ppb, and adding a very little bit of code from "Ultimate" for the power warning light.

TODO: Setting for the variable power port. It can be turned on and off here (1/0) but the PPBA also accepts a voltage in the same field.
TODO: I didn't modify the simulator.

It also seems to me that the lights should show in AstroImager at the bottom of the window, but they do not show.

### CODE REVIEW

**Comment by aaronfreimark** [comment]
I noticed the light does show in AstroImager 3.x, so perhaps there was a change to AI 4.

**Comment by rumengb** [comment]
I have several concerns about the pull request.
1.it contains bimaty file fxload whish should not be there. 
2. Maybe it is a better idea to extend the current ppb driver rather than creating a new one..
Because of  the first reason we can not accept this pull request.

**Comment by aaronfreimark** [comment]
@rumengb Thank you for this feedback. I've been working in commercial software my entire career, not as a developer though. And this is my first pull request! Thank you for maintaining a product that inspired my entry into open source!

I do appreciate the constructive comments, and I'll put more effort into the code. I will submit again once it is improved.

**Comment by rumengb** [comment]
@aaronfreimark welcome to open source, and thank you for the nice words :) I am glad you want to contribute and we are waiting for your ppb driver update :)
I am also glad you were not offended  by my comments :) Some people take this quite personal and i feel uncomfortable to comment and refuse code. So do not get discouraged! Waiting fir your contribution and who knows you may become a regular contributor which would be great :)

**Comment by polakovic** [comment]
Hi, Rumen is right, it will be MUCH easier to change indigo_aux_ppb driver to works with both standard and advanced powerbox (the same way as indigo_aux_upb driver works with both v1 and v2 UPB). I'm on a vacation until end of next week so if you want, you can try to change the driver. If you want just test it, I'll do it as soon as I'll be back :)

**Pull request closed without merging**
