### PR TITLE
ccd_ptp: fix canon compression

### PR DESCRIPTION
**Pull request by tail-feather**
Nikon and Sony have `DSLR_COMPRESSION`, but Canon does not.

And added `CRAW` (0x10060003, Compact RAW) label .

Before:
```
<defSwitchVector device="Canon EOS R #0206" name="CCD_MODE" group="Camera" label="Capture mode" perm="rw" state="Ok" rule="OneOfMany">
	<defSwitch name="10010003" label="Large fine JPEG">Off</defSwitch>
	<defSwitch name="10010002" label="Large JPEG">Off</defSwitch>
	<defSwitch name="10010103" label="Medium fine JPEG">Off</defSwitch>
	<defSwitch name="10010102" label="Medium JPEG">Off</defSwitch>
	<defSwitch name="10010e03" label="S1 fine JPEG">Off</defSwitch>
	<defSwitch name="10010e02" label="S1 JPEG">Off</defSwitch>
	<defSwitch name="10010f03" label="S2 fine JPEG">Off</defSwitch>
	<defSwitch name="1006000410010003" label="RAW + Large fine JPEG">On</defSwitch>
	<defSwitch name="1006000410010002" label="RAW + Large JPEG">Off</defSwitch>
	<defSwitch name="1006000410010103" label="RAW + Medium fine JPEG">Off</defSwitch>
	<defSwitch name="1006000410010102" label="RAW + Medium JPEG">Off</defSwitch>
	<defSwitch name="1006000410010e03" label="RAW + S1 fine JPEG">Off</defSwitch>
	<defSwitch name="1006000410010e02" label="RAW + S1 JPEG">Off</defSwitch>
	<defSwitch name="1006000410010f03" label="RAW + S2 fine JPEG">Off</defSwitch>
	<defSwitch name="1006000310010003" label="RAW + S2 fine JPEGLarge fine JPEG">Off</defSwitch>
	<defSwitch name="1006000310010002" label="RAW + S2 fine JPEGLarge fine JPEGLarge JPEG">Off</defSwitch>
	<defSwitch name="1006000310010103" label="RAW + S2 fine JPEGLarge fine JPEGLarge JPEGMedium fine JPEG">Off</defSwitch>
	<defSwitch name="1006000310010102" label="RAW + S2 fine JPEGLarge fine JPEGLarge JPEGMedium fine JPEGMedium JPEG">Off</defSwitch>
	<defSwitch name="1006000310010e03" label="RAW + S2 fine JPEGLarge fine JPEGLarge JPEGMedium fine JPEGMedium JPEGS1 fine JPEG">Off</defSwitch>
	<defSwitch name="1006000310010e02" label="RAW + S2 fine JPEGLarge fine JPEGLarge JPEGMedium fine JPEGMedium JPEGS1 fine JPEGS1 JPEG">Off</defSwitch>
	<defSwitch name="1006000310010f03" label="RAW + S2 fine JPEGLarge fine JPEGLarge JPEGMedium fine JPEGMedium JPEGS1 fine JPEGS1 JPEGS2 fine JPEG">Off</defSwitch>
	<defSwitch name="10060004" label="RAW">Off</defSwitch>
	<defSwitch name="10060003" label="">Off</defSwitch>
</defSwitchVector>
```

After:
```
<defSwitchVector device="Canon EOS R #0206" name="DSLR_COMPRESSION" group="DSLR" label="Compression" perm="rw" state="Ok" rule="OneOfMany">
	<defSwitch name="10010003" label="Large fine JPEG">Off</defSwitch>
	<defSwitch name="10010002" label="Large JPEG">Off</defSwitch>
	<defSwitch name="10010103" label="Medium fine JPEG">Off</defSwitch>
	<defSwitch name="10010102" label="Medium JPEG">Off</defSwitch>
	<defSwitch name="10010e03" label="S1 fine JPEG">Off</defSwitch>
	<defSwitch name="10010e02" label="S1 JPEG">Off</defSwitch>
	<defSwitch name="10010f03" label="S2 fine JPEG">Off</defSwitch>
	<defSwitch name="1006000410010003" label="RAW + Large fine JPEG">Off</defSwitch>
	<defSwitch name="1006000410010002" label="RAW + Large JPEG">Off</defSwitch>
	<defSwitch name="1006000410010103" label="RAW + Medium fine JPEG">Off</defSwitch>
	<defSwitch name="1006000410010102" label="RAW + Medium JPEG">Off</defSwitch>
	<defSwitch name="1006000410010e03" label="RAW + S1 fine JPEG">Off</defSwitch>
	<defSwitch name="1006000410010e02" label="RAW + S1 JPEG">Off</defSwitch>
	<defSwitch name="1006000410010f03" label="RAW + S2 fine JPEG">Off</defSwitch>
	<defSwitch name="1006000310010003" label="CRAW + Large fine JPEG">Off</defSwitch>
	<defSwitch name="1006000310010002" label="CRAW + Large JPEG">Off</defSwitch>
	<defSwitch name="1006000310010103" label="CRAW + Medium fine JPEG">Off</defSwitch>
	<defSwitch name="1006000310010102" label="CRAW + Medium JPEG">Off</defSwitch>
	<defSwitch name="1006000310010e03" label="CRAW + S1 fine JPEG">On</defSwitch>
	<defSwitch name="1006000310010e02" label="CRAW + S1 JPEG">Off</defSwitch>
	<defSwitch name="1006000310010f03" label="CRAW + S2 fine JPEG">Off</defSwitch>
	<defSwitch name="10060004" label="RAW">Off</defSwitch>
	<defSwitch name="10060003" label="CRAW">Off</defSwitch>
</defSwitchVector>
```

### CODE REVIEW

**Comment by polakovic** [comment]
Unfortunately, this change is not compatible with the existing clients. With Nikon, the capture mode (= image size) is one PTP property and the compression (= normal/fine) is another. But with Canon it is a single property so both is included in the capture mode. Nevertheless, in INDIGO, capture mode is mandatory property, while compression is not. So if there is just one property, it should be the "capture mode" and not the "compression". 

The change related to CRAW is hopefully correct, but it would be good to add some default branch to each case to set the label to something like "unknown". Maybe canon will invent some new format with next cameras :)

**Comment by tail-feather** [comment]
Oh I see. Reverted Canon `DSLR_COMPRESSION`.
And added `Unknown (0x%x)` labels.

**Comment by tail-feather** [comment]
By the way, SONY does not have `CCD_MODE`, but` DSLR_COMPRESSION` does.

**Comment by polakovic** [comment]
Ooops, that SONY is probably my bug :) I'll fix it.

**Comment by polakovic** [comment]
I checked it, SONY is the same as NIKON, it has both DSLR_CAPTURE_MODE_PROPERTY_NAME (line 76) and DSLR_COMPRESSION_PROPERTY_NAME (line 68). It is probably correct.

**Pull request merged**
